### ISSUE TITLE
Solve Diffrences between SignIn & SignUp Pages.

### ISSUE THREAD

**Issue by Anshul-004** [Anshul-004/GoRSVP#10]
Heading font size, text color shade (For URI's - Forgot Password etc) and SignUp & SignIn Link on pages, donot work.

**Comment by Ayushwan2004** [comment]
solved  /assign me

**Comment by Ayushwan2004** [comment]
solves #10

**Comment by Ayushwan2004** [comment]
> solved /assign me

Solved #10
